# Author: NSSA Group 6 Security Team
# Purpose: To test security vulnerabilities of our deployments
# Date 9/17/2023
# Version: 1.0

- name: Security Vulnerabilities Test
  hosts: test
  gather_facts: false
  tasks:
    - name: Attempt Directory Listing
      ansible.builtin.uri:
        url: "http://web-test/resources/"
        method: GET
      register: directory_listing_result
      ignore_errors: true

    - name: Attempt to get ETAG header
      ansible.builtin.shell: "curl -I -s http://web-test"
      register: curl_response

    - name: Print response
      ansible.builtin.debug:
        var: curl_response

    - name: "fail early"
      fail:
        msg: "Bruh because"

    - name: Check for ETag Header
      ansible.builtin.debug:
        msg: "ETag header is {{ 'present' if 'ETag' in curl_response.stdout else 'not present' }}"

    - name: Check for Server Header
      ansible.builtin.debug:
        msg: "Server header is present on the server."
      when: "'Server' in curl_response.stdout"

    - name: Check for Server Header Absence
      ansible.builtin.debug:
        msg: "Server header is not present on the server."
      when: "'Server' not in curl_response.stdout"

    - name: Send HTTP TRACE Request
      ansible.builtin.uri:
        url: "http://web-test"
        method: TRACE
      register: trace_response

    - name: Check TRACE Request Response
      debug:
        msg: "TRACE requests are allowed on the server."
      when: "trace_response.status == 200"
      register: trace_response_result

    - name: Check TRACE Request Response
      debug:
        msg: "TRACE requests are not allowed on the server. Status code: {{ trace_response.status }}"
      when: "trace_response.status != 200"
      register: trace_response_result

    - name: Check Firewall Service Status
      ansible.builtin.shell: "systemctl status firewalld | grep -oP 'Active: \\K\\w+'"
      register: firewall_status

    - name: Display Firewalld Status
      debug:
        msg: "Firewalld is {{ 'enabled' if firewall_status else 'disabled' }}"
