# Author: NSSA Group 6 Security Team
# Purpose: To test security vulnerabilities of our deployments
# Date 9/17/2023
# Version: 1.0

- name: Security Vulnerabilities Test
  hosts: test
  gather_facts: false
  tasks:
    - name: Attempt Directory Listing
      ansible.builtin.uri:
        url: "http://192.168.206.151/resources/"
        method: GET
      register: directory_listing_result
      ignore_errors: true

    - name: Attempt to get ETAG header
      ansible.builtin.uri:
        url: "http://192.168.206.151"
        method: GET
      register: http_response

    - name: Check for ETag Header
      ansible.builtin.debug:
        msg: "ETag header is {{ 'present' if 'ETag' in http_response.headers else 'not present' }}"

    # Both based on Test server IP
    - name: Attempt to Fetch Server Signature
      ansible.builtin.uri:
        url: "http://192.168.206.151"
        method: GET
      register: server_signature_result
      ignore_errors: true

    - name: Send HTTP TRACE Request
      ansible.builtin.uri:
        url: "http://192.168.206.151/index.html"
        method: TRACE
      register: http_trace_response
      ignore_errors: true

    - name: Check for TRACE Response Headers
      ansible.builtin.debug:
        msg: "Cross-Site Tracing (XST) is possible!"
      when: "'TRACE' in http_trace_response.url"

    - name: Check Firewall Service Status
      ansible.builtin.service:
        name: firewalld
        state: started
        register: firewall_status

    - name: Display Firewall Status
      ansible.builtin.debug:
        var: firewall_status

    - name: Display Vulnerability Test Results
      ansible.builtin.debug:
        var: item.stdout_lines
      with_items:
        - "{{ directory_listing_result }}"
        - "{{ server_signature_result }}"
        - "{{ http_response }}"
        - "{{ http_trace_response }}"
      when: "'404 Not Found' not in item.stdout"
