# Author: NSSA-320 Group 6 Operations Team
# Purpose: Use B servers for load balancer
# Date: 10/17/2023
# Version: 1

- hosts: web_loadbalancer
  become: true
  tasks:
    - name: Update haproxy to use secondary servers
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        marker: "{mark}"
        marker_begin: "# ANSIBLE START"
        marker_end: "# ANSIBLE END"
        block: |
          backend web_back
            balance roundrobin
            server web_prod_2a 192.168.197.48:80 check
            server web_prod_2b 192.168.193.102:80 check
            server web_prod_2c 192.168.205.223:80 check

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
