# Author: NSSA-320 Group 6 Operations Team
# Purpose: Use A servers for load balancer
# Date: 10/17/2023
# Version: 1

- hosts: web_loadbalancer
  become: true
  tasks:
    - name: Update haproxy to use primary servers
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        marker: "{mark}"
        marker_begin: "# ANSIBLE START"
        marker_end: "# ANSIBLE END"
        block: |
          backend web_back
            balance roundrobin
            server web_prod_1a 192.168.206.152:80 check
            server web_prod_1b 192.168.205.223:80 check
            server web_prod_1c 192.168.199.237:80 check

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
