# Author: NSSA320 Group 6 Operations (and security) Team(s)
# Purpose: To test stability under load of our web servers
# Date 9/18/2023
# Version: 1.0

- name: Load test web server
  hosts: siege_server
  become: true
  vars: 
    web_server_ip: "192.168.204.95"
    num_simul_users: 200
    time: "1m"
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install Siege
      yum:
        name: siege
        state: present

    - name: Add URL to siege configuration
      ansible.builtin.shell: 'echo "{{web_server_ip}}" > /etc/siege/urls.txt'
      become: true

    - name: Make sure logging directory exists
      ansible.builtin.file:
        path: /var/log/siege
        state: directory
        mode: "0755"

    - name: Remove siege log file
      ansible.builtin.file:
        path: /var/log/siege/siege.log
        state: absent

    - name: Run siege against server
      ansible.builtin.command: "siege -c {{num_simul_users}} -t {{time}} --log=/var/log/siege/siege.log"

    - name: Display siege results
      ansible.builtin.shell: "cat /var/log/siege/siege.log"
      register: log_contents

    - name: Print log file contents
      ansible.builtin.debug:
        var: log_contents.stdout_lines
