- name: Load test web server
  hosts: siege_server
  become: true
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install Siege
      yum:
        name: siege
        state: present

    - name: Add URL to siege configuration
      ansible.builtin.shell: 'echo "http://web-test" > /etc/siege/urls.txt'
      become: true

    - name: Run siege against server
      ansible.builtin.command: "siege -c 100 -t 1m"
      register: siege_result

    - name: Display siege result
      debug:
        var: siege_result
