# Author: NSSA320 Group 6 Operations Team
# Purpose: To test stability under load of our web servers
# Date 9/18/2023
# Version: 1.0

- name: Load test web server
  hosts: siege_server
  become: true
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install Siege
      yum:
        name: siege
        state: present

    - name: Add URL to siege configuration
      ansible.builtin.shell: 'echo "http://192.168.194.81" > /etc/siege/urls.txt'
      become: true

    - name: Make sure logging directory exists
      ansible.builtin.file:
        path: /var/log/siege
        state: directory
        mode: "0700"

    - name: Run siege against server
      ansible.builtin.command: "siege -c 100 -t 10s --log=/var/log/siege/siege.log"
      register: siege_result
