- name: Load test web server
  hosts: siege_server
  become: true
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install Siege
      yum:
        name: siege
        state: present

    - name: Add URL to siege configuration
      ansible.builtin.shell: 'echo "http://web-test" > /etc/siege/urls.txt'
      become: true
