- name: Install and Start Zabbix
  hosts: Zabbix
  become: yes
  tasks:
    - name: Install Zabbix repository RPM
      yum:
        name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
        state: present
        disable_gpg_check: true
    
    - name: Install Zabbix Server, Agent, and Frontend
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent

    - name: Configure Zabbix Server
      template:
        src: templates/zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
      notify:
        - restart zabbix server

    - name: Configure PHP Settings for Zabbix
      template:
        src: templates/zabbix_php.ini.j2
        dest: /etc/php.ini
      notify:
        - restart apache

    - name: Start and Enable Zabbix Server and Agent
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - zabbix-server
        - zabbix-agent

  handlers:
    - name: restart zabbix server
      systemd:
        name: zabbix-server
        state: restarted

    - name: restart apache
      systemd:
        name: httpd
        state: restarted
