- name: Install Zabbix on CentOS 7
  hosts: Zabbix
  become: yes  # Use sudo to execute commands as root

  tasks:
    - name: Install Zabbix repository RPM
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb 
        state: present
        
    - name: Install shell
      ansible.builtin.command: dpkg -i zabbix-release_5.0-1+focal_all.deb

    - name: Install Zabbix Server and Agent
      yum:
        name:
          - zabbix-server-mysql
          - zabbix-agent
        state: present

    - name: Start and enable Zabbix services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - zabbix-server
        - zabbix-agent
