# Author: NSSA Group 6 Security Team
# Purpose: To test security vulnerabilities of our deployments
# Date 9/17/2023
# Version: 1.0

- name: Security Vulnerabilities Test
  hosts: test
  gather_facts: false
  tasks:
    - name: Attempt Directory Listing
      ansible.builtin.uri:
        url: "http://web-test/resources/"
        method: GET
      register: directory_listing_result
      ignore_errors: true

    - name: Attempt to get ETAG header
      ansible.builtin.shell: "curl -I -s http://web-test"
      register: curl_response

    - name: Check for ETag Header
      ansible.builtin.debug:
        msg: "ETag header is {{ 'present' if 'ETag' in curl_response.stdout else 'not present' }}"

    - name: Check for Server Header
      ansible.builtin.debug:
        msg: "Server header is present on the server."
      when: "'Server' in curl_response.stdout"

    - name: Check for Server Header Absence
      ansible.builtin.debug:
        msg: "Server header is not present on the server."
      when: "'Server' not in curl_response.stdout"

    - name: Send HTTP TRACE Request
      ansible.builtin.uri:
        url: "http://web-test"
        method: TRACE
      register: trace_response

    - name: Check TRACE Request Response
      debug:
        msg: "TRACE requests are allowed on the server."
      when: "trace_response.status == 200"
      register: trace_response_result

    - name: Check TRACE Request Response
      debug:
        msg: "TRACE requests are not allowed on the server. Status code: {{ trace_response.status }}"
      when: "trace_response.status != 200"
      register: trace_response_result

    - name: Check Firewall Service Status
      ansible.builtin.shell: "systemctl status firewalld | grep -oP 'Active: \\K\\w+'"
      register: firewall_status

    - name: Display Firewalld Status
      debug:
        msg: "Firewalld is {{ 'enabled' if firewall_status else 'disabled' }}"

#Original Tests above^^
#Lab 2 tested added below
    - name: Test for Released Candidates
      hosts: your_web_servers
      tasks:
        - name: Test for RC1
          uri:
            url: "http://web-test"
            method: GET
          register: rc1_response
          ignore_errors: yes

        - name: Report RC Versions
          debug:
            msg: "Released Candidate found: {{ item.url }}"
          when: item.status == 200
#extented tests for lab 3
      - hosts: all
        become: yes
        tasks:
        - name: Check if SSL is open
          uri:
            url: "https://web-test"
            validate_certs: no
            status_code: 200
          register: ssl_result

        - name: Fail if SSL is not open
          fail:
            msg: "SSL is not open on {{ item.url }}"
          when: ssl_result.status != 200